-- 2.0 vault: one row per encrypted item, synced incrementally by revision.
-- The server only ever stores ciphertext (`encrypted_item` is the client's
-- { v, key, data } record as JSON text); ids are generated by the client.

CREATE SEQUENCE vault_revision_seq;

CREATE TABLE vault_items (
  id               UUID        PRIMARY KEY,
  owner_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Team collections land in a later migration (FK added there).
  collection_id    UUID        NULL,
  -- Empty once deleted: the tombstone keeps only id + revision.
  encrypted_item   TEXT        NOT NULL,
  -- Set by the client (the server can't read the item): false for logins that
  -- only hold a 2FA code, which don't count toward the Free item limit.
  counts_for_limit BOOLEAN     NOT NULL DEFAULT TRUE,
  -- Global, monotonically increasing: clients pull "everything after N".
  revision         BIGINT      NOT NULL DEFAULT nextval('vault_revision_seq'),
  deleted_at       TIMESTAMPTZ NULL,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX vault_items_owner_revision ON vault_items (owner_id, revision);

-- 1 = v1 blob in `accounts`; 2 = migrated to vault_items.
ALTER TABLE users ADD COLUMN vault_version SMALLINT NOT NULL DEFAULT 1;
